/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'outputType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'conversationHistory' : IDL.Vec(Message),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'outputType' : IDL.Text,
  'generatedHTML' : IDL.Text,
});
export const MessageInput = IDL.Record({
  'projectId' : IDL.Nat,
  'message' : IDL.Text,
  'imageBase64' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([ProjectInput], [IDL.Nat], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGeneratedHTML' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjectIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAiResponse' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJsonApiError' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Record({ 'type' : IDL.Text, 'message' : IDL.Text }),
      ],
      [],
      [],
    ),
  'sendMessageToAI' : IDL.Func(
      [MessageInput],
      [
        IDL.Record({
          'apiKey' : IDL.Text,
          'requestJson' : IDL.Text,
          'project' : Project,
        }),
      ],
      [],
    ),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProject' : IDL.Func([IDL.Nat, ProjectInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'outputType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'conversationHistory' : IDL.Vec(Message),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'outputType' : IDL.Text,
    'generatedHTML' : IDL.Text,
  });
  const MessageInput = IDL.Record({
    'projectId' : IDL.Nat,
    'message' : IDL.Text,
    'imageBase64' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([ProjectInput], [IDL.Nat], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGeneratedHTML' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjectIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAiResponse' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJsonApiError' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Record({ 'type' : IDL.Text, 'message' : IDL.Text }),
        ],
        [],
        [],
      ),
    'sendMessageToAI' : IDL.Func(
        [MessageInput],
        [
          IDL.Record({
            'apiKey' : IDL.Text,
            'requestJson' : IDL.Text,
            'project' : Project,
          }),
        ],
        [],
      ),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProject' : IDL.Func([IDL.Nat, ProjectInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };